### PR TITLE
Create docker flow for github

### PR DESCRIPTION
**Pull request by doob187**
Rename Tauticord  to tauticord
Add CR_PAT under repository secrets

### CODE REVIEW

**Comment by doob187** [comment]
Ask @cyber for instructions

**Comment by doob187** [comment]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by nwithan8** [comment]
I was just thinking today that I wanted to finally get around to showing some love to the Docker image.
Can you explain what this workflow does, and what the contributor portion is?

**Comment by doob187** [comment]
Its builded the images for GHRC.io 
The contribution lines 

Added automatically all users they pushed some changes to  list

**Comment by nwithan8** [comment]
@doob187 Can we make it so that this workflow runs on release rather than on non-PR pushes?

**Comment by doob187** [comment]
```sh
version="$(curl -u $username:$token -sX GET "https://api.github.com/repos/nwithan8/tauticord/releases/latest" | jq --raw-output '.tag_name')"
version="${version#*v}"
version="${version#*release-}"
printf "%s" "${version}"

```

You need to make releases

**Comment by doob187** [comment]
Or add in each step 

```sh
if: github.event_name != 'pull_request'
```

**Comment by doob187** [comment]
You can also ask  hawkinzz  ;)

**Comment by nwithan8** [comment]
Can you explain why I should use GHRC when I'm already using Docker Hub?

**Pull request closed without merging**
