### PR TITLE
Added EnvironmentVariable checks to the configParser.py for Unraid docker configs

### PR DESCRIPTION
**Pull request by Znomon**
When deploying as a docker container on UnRaid, the container would crash due to not having a config.yaml file. These containers come from dockerhub.

Standard procedure for these kinds of issues on UnRaid is either a webGUI or Docker Environment Variables for setting user-specific config values like API keys, etc.

This pull request adds checks to see if Environment variables are set, and if so, changes the config of the bot to use those values. It checks each variable so not all are required, and if none are set, the configuration file is read normally.

has been tested and confirmed working using portainer and pulling directly from dockerhub. Updated README to clarify setup using UnRaid

### CODE REVIEW

**Comment by Znomon** [comment]
@nwithan8 this is my first PR to a public repo, let me know if you need anything from me. It is tested and ready to be merged.

**Comment by nwithan8** [comment]
Fantastic, I was just about to look into improving configuration when using the bot as a Docker container.
If you could fix the conflicts on `config_parser.py`, we should be good to merge!

**Comment by Znomon** [comment]
@nwithan8 looks like it won't let me resolve the conflicts without write access to the repo?

**Comment by nwithan8** [comment]
You will need to rebase your branch onto my master branch to resolve those conflicts.

Sorry, I've been busy this past week. I'll try to take a look at this this week.

**Comment by Znomon** [comment]
no worries, we all are busy, it took me over half a year to get back to this. I will try and get to it this week too lol. The good news, this PR works, the bot has been running flawlessly on unraid in a docker container since January. At least I got that going for me.

**Comment by Znomon** [comment]
Alright, I rebased it. Should be good to go. @nwithan8

**Comment by nwithan8** [comment]
Thanks for the help. I went ahead and implemented this in #34

**Pull request closed without merging**
