### PR TITLE
Insignificant change to output formatting

### PR DESCRIPTION
**Pull request by twilsonco**
Subtle change to output formatting to make it a bit more readable.

### CODE REVIEW

**Comment by twilsonco** [comment]
Bugfix: reactions weren't being removed when no activity.
Feature: better printing of live tv sessions.

**Review by nwithan8 — APPROVED** [review]

**Review by nwithan8 — CHANGES_REQUESTED** [review]
What is the discord_connectory copy file?

**Comment by nwithan8** [comment]
Recommended changes have been included in a new update, thanks!
Closing this PR.

**Comment by twilsonco** [comment]
Oops, forget about that file. My industry standard style of making a local copy instead of utilizing proper version control.

**Pull request closed without merging**
